### PR TITLE
repomapping: Add RHEL7 ELS repos

### PR DESCRIPTION
**Pull request by matejmatuska**
RHEL-21891

**BEFORE MERGE:** Make sure this is merged together with https://github.com/oamg/schema-test/pull/14 and also the repomap.json is merged internally.

### CODE REVIEW

**Comment by matejmatuska** [comment]
Tested on a RHEL7 machine with ELS subscription, with the following repos enabled (OAMG COPR repo left out and sensitive data cut out):
```
Repo-id      : rhel-7-server-els-rpms/x86_64
Repo-name    : Red Hat Enterprise Linux 7 Server - Extended Life Cycle Support (RPMs)
--- 8< ---

Repo-id      : rhel-7-server-extras-rpms/x86_64
Repo-name    : Red Hat Enterprise Linux 7 Server - Extras (RPMs)
--- 8< ---
```

After running `leapp preupgrade` the repos are mapped to rhel8 GA repos, as expected 
```shell
# ./leapp-inspector messages --type TargetRepositories
######################################################################
                          PRODUCED MESSAGES
######################################################################
Stamp: 2024-04-15T16:01:33.601493Z
Actor: setuptargetrepos
Phase: FactsCollection
Type: TargetRepositories
Message_data:
{
    "custom_repos": [],
    "rhel_repos": [
        {
            "repoid": "rhel-8-for-x86_64-appstream-rpms"
        },
        {
            "repoid": "rhel-8-for-x86_64-baseos-rpms"
        }
    ]
}
######################################################################

```

**Comment by pirat89** [comment]
Postponing the testing for monday. But lgtm otherwise, including changes in schema.

**Comment by pirat89** [comment]
Discussed with @vojtechsokol, merging would negatively affect RUT. Postponing the merging by 1-2d.

**Review by pirat89 — APPROVED** [review]
lgtm and it seems to work as expected. merging. all other MRs/PRs have been merged too.

**Pull request merged**
