### PR TITLE
Grubby debug was failing on s390x

### PR DESCRIPTION
**Pull request by Rezney**
For some reason the sed command was not working on s390x.
Switching to python.

### CODE REVIEW

**Comment by Rezney** [comment]
Have to test this first...

**Comment by AloisMahdal** [comment]
e2e tests

**Comment by AloisMahdal** [comment]
e2e tests

**Comment by Rezney** [comment]
Seems to be working fine as @pirat89 witnessed :) @AloisMahdal can we get a clean run here?

**Comment by AloisMahdal** [comment]
> For some reason..

FYI, the reason was that `/usr/bin/grubby` did not exist.

**Comment by Rezney** [comment]
e2e tests

**Comment by Rezney** [comment]
@AloisMahdal traceback or some snippet might be useful...

**Comment by Rezney** [comment]
@AloisMahdal test "murphy-ci/upgrade Pending — lpr=R415" has been in pending state for more than 5 hours...

**Comment by AloisMahdal** [comment]
The reason it was 5h running was because it was in emergency mode due to a known issue: current leapp-repository `U`pstream master is not already compatible with leapp's latest release (`B`rew build, downstream), which is what Murphy CI picks up by default.  (We're going to discuss this choice later.)

Nevertheless,I've re-ran the whole thing manually with leapp `U`pstream master build but I got strange traceback from RHSM; reporting downstream.

As an aside, because the earlier result took over 8h (we're generous with timeout) it overrode the later one which ran only about 1-2h.  Since both results are invalid this almost does not matter now; it's just why the status description is different (`lpr=R415` vs `lpr=R415,lp=U`).

For now I have re-ran it again, hoping that the RHSM issue was an intermittent one.

**Comment by AloisMahdal** [comment]
Now upgrade batches passed but integration+static failed due to Fedora COPR outage.

(I don't know how this works.  It's magic. Apparently calling our CI Murphy was way more fitting than we wanted; this PR is the first one where we're reporting back to GH and it's all on fire. (@vinzenz this was inspired by your remark so explain yourself you sorcerer! :-D))

Note that at this point we saw pass in every batch, with same build set, but I am going to re-run it again now so that if we're lucky in the morning Rezney could see a clean run.

**Pull request merged**
