### PR TITLE
Skip test which rely on dnf package if dnf is unavailable

### PR DESCRIPTION
**Pull request by ZhukovGreen**
This is a small MR linked with recent #525 (already merged). After merging #525, the tests are failing on systems which don't have dnf package.

This MR resolves this problem

### CODE REVIEW

**Comment by drehak** [comment]
Is it okay to skip the test? IMHO a better solution would be just to mock `get_repodirs` as a function or a lambda returning `['/etc/yum.repos.d']`. That's the only part that requires importing `dnf`, so the rest of the should run just like before.

**Comment by drehak** [comment]
Oh, I see it's merged now. Nevermind then.

**Comment by bocekm** [comment]
I also think this could be done better. Setting a constant in the code which is used **only** in a test seems unclean to me.

**Comment by ZhukovGreen** [comment]
@bocekm @drehak agree with you guys, I did it too fast. Fixing it right now

**Comment by ZhukovGreen** [comment]
@fellipeh sorry Fellipe, for urging you

**Pull request merged**
