### PR TITLE
Do not use the deprecated logger.warn method

### PR DESCRIPTION
**Pull request by pirat89**
The logger.warn method has been deprecated since Python 3.3.
Developers are supposed to use the logger.warning method instead.
See:
    https://github.com/python/cpython/blob/3.3/Lib/logging/__init__.py#L1252-L1253
    https://bugs.python.org/issue13235

Deprecates:
    produce_mocked.warn from leapp.libraries.common.testutils

### CODE REVIEW

**Comment by pirat89** [comment]
Let's call it cute:
```
AttributeError: module 'warnings' has no attribute 'warning'
```

For `logging` use `warning`, for `warnings` use `warn`. That's design.

**Comment by pirat89** [comment]
@Rezney  ok, it seems it could work :)

**Comment by pirat89** [comment]
e2e tests

**Comment by examon** [comment]
leapp-ci build

**Review by Rezney — APPROVED** [review]
Looks good to me. Let's wait for the last part of the pipeline to pass.

**Comment by pirat89** [comment]
leapp-ci build

**Comment by vojtechsokol** [comment]
e2e tests

**Pull request merged**
