### PR TITLE
Remove transaction check actor

### PR DESCRIPTION
**Pull request by asilveir**
- This actor just gives almost the same error than the upgrade transaction actor.
- Removed to save some upgrade execution time.

### CODE REVIEW

**Comment by vinzenz** [comment]
The point of this actor is actually to include those problems in the report eventually. There is no point of removing the actor.

**Comment by Rezney** [comment]
I could imagine that we would skip running the check with `leapp upgrade` but it is essential for `leapp-preupgrade`.

We should definitely not remove it...

**Comment by Rezney** [comment]
We discussed this with @pirat89 and we will need this also in `leapp upgrade` cause we do not differentiate `preupgrade` and `upgrade` in terms of reporting.

**Comment by bocekm** [comment]
Improved solution: https://github.com/oamg/leapp-repository/pull/349

**Pull request closed without merging**
