### PR TITLE
Do not run grub2-editenv cmd on s390x systems

### PR DESCRIPTION
**Pull request by Rezney**
s390x systems use zipl instead of grub

### CODE REVIEW

**Comment by fellipeh** [comment]
e2e

**Comment by fellipeh** [comment]
e2e tests

**Comment by fellipeh** [comment]
LGTM waiting for e2e tests finish

**Comment by AloisMahdal** [comment]
integration failed because machine (with rather funny hostname `intel-lizardhead*`) totally failed to even start setup.  I've reported the machine and will re-run tests immediately.  Sorry for inconvenience.

**Pull request merged**
