### PR TITLE
Change the upgrade path for SAP HANA 7->8

### PR DESCRIPTION
**Pull request by pirat89**
iow:
   7.9 -> 8.2 (default), 8.6
   8.6 -> 9.0

* The RHEL 8.4 is not going to be supported
  for in-place upgrades with SAP HANA.
  Instead of that, the supported target
  releases are 8.2 and 8.6.

  As well, the 8.2 stays as default for the
  saphana flavour as 8.6 is not certified
  everywhere yet.
  * RHELBU-1759
  * RHELBU-1762

* Introduce upgrade path 8.6 -> 9.0 with SAP HANA
  * RHELBU-1747
  * RHELBU-1763

### CODE REVIEW

**Comment by alexxa** [comment]
@pirat89 I installed from master, and then updated upgraded_path.json file. And in the end, it doesn't work for me on Azure, and shows 8.4 and 8.6 only options. To me, it seems like it doesn't see SAP paths, but base RHEL. Did I miss smth? 

```
$ sudo leapp preupgrade --no-rhsm --target 8.2 --enablerepo rhel-8-for-x86_64-appstream-e4s-rhui-rpms --enablerepo rhel-8-for-x86_64-baseos-e4s-rhui-rpms --enablerepo microsoft-azure-rhel8-sap-ha
usage: leapp preupgrade [-h] [--report-schema {1.0.0,1.1.0}]
                        [--target {8.4,8.6}] [--channel {ga,tuv,e4s,eus,aus}]
                        [--enablerepo <repoid>] [--no-rhsm] [--verbose]
                        [--debug] [--whitelist-experimental ActorName]

Description:

Generate preupgrade report

Optional arguments:
  -h, --help            show this help message and exit
  --report-schema {1.0.0,1.1.0}
                        Specify report schema version for leapp-report.json
  --target {8.4,8.6}    Specify RHEL version to upgrade to for default
                        detected upgrade flavour
  --channel {ga,tuv,e4s,eus,aus}
                        Set preferred channel for the IPU target.
  --enablerepo <repoid>
                        Enable specified repository. Can be used multiple
                        times.
  --no-rhsm             Use only custom repositories and skip actions with Red
                        Hat Subscription Manager
  --verbose             Enable verbose logging
  --debug               Enable debug mode
  --whitelist-experimental ActorName
                        Enables experimental actors
error: argument --target: invalid choice: '8.2' (choose from u'8.4', u'8.6')
$ sudo cat /usr/share/leapp-repository/repositories/system_upgrade/common/files/upgrade_paths.json
{
    "default": {
        "7.6": ["8.4", "8.6"],
        "7.9": ["8.4", "8.6"],
        "8.6": ["9.0"],
        "7": ["8.4", "8.6"],
        "8": ["9.0"]
    },
    "saphana": {
        "7.9": ["8.6", "8.2"],
        "7": ["8.6", "8.2"],
        "8.6": ["9.0"],
        "8": ["9.0"]
    }
}
$ rpm -qa leapp*
leapp-upgrade-el7toel8-deps-0.15.0-100.20220216151445731647.master.82.gbd85b9b.el7.noarch
leapp-rhui-azure-sap-1.0.0-1.el7.noarch
leapp-0.13.0-100.20220214090910234539.master.19.g94d5f7a.el7.noarch
leapp-deps-0.13.0-100.20220214090910234539.master.19.g94d5f7a.el7.noarch
leapp-upgrade-el7toel8-0.15.0-100.20220216151445731647.master.82.gbd85b9b.el7.noarch
$ rpm -qa *sap*
leapp-rhui-azure-sap-1.0.0-1.el7.noarch
rhui-azure-rhel7-base-sap-ha-2.2-222.noarch
```
CC @Rezney

**Comment by pirat89** [comment]
@alexxa here is the function that does the detection:
* https://github.com/oamg/leapp-repository/blob/bd85b9bc2ee2d340f8cf875c8b7eeba9aae1f391/commands/command_utils.py#L44

Can you confirm that on the system exists a path like:
```
/hana/shared/*/exe/linuxx86_64/hdb/sapcontrol
```

**Comment by alexxa** [comment]
@Rezney see, there is not sense to run it without HANA installed =) I see the idea behind checking for that file, nevertheless WDYT about `--product` arg? 

@pirat89 when I tried for `preupgrade  --target 8.6`, there was an error below. Any chance to fail it more gracefully/informative, i.e. that the target release is not available/repos are missing? 

```
Red Hat Enterprise Linux 8 for x86_64 - BaseOS  0.0  B/s |   0  B     00:00    
Microsoft Azure RPMs for RHEL8 High Availabilit  39 kB/s | 1.7 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - AppStre 0.0  B/s |   0  B     00:00    
No match for argument: dnf
No match for argument: dnf-command(config-manager)

============================================================
                           ERRORS                           
============================================================

2022-02-20 23:45:26.779958 [ERROR] Actor: target_userspace_creator
Message: Unable to install RHEL 8 userspace packages.
Summary:
    Details: Command ['systemd-nspawn', '--register=no', '--quiet', '-D', '/var/lib/leapp/scratch/mounts/root_/system_overlay', '--setenv=LEAPP_UPGRADE_PATH_TARGET_RELEASE=8.6', '--setenv=LEAPP_NO_RHSM=1', '--setenv=LEAPP_EXPERIMENTAL=0', '--setenv=LEAPP_UPGRADE_PATH_FLAVOUR=saphana', '--setenv=LEAPP_COMMON_TOOLS=:/etc/leapp/repos.d/system_upgrade/el7toel8/tools', '--setenv=LEAPP_COMMON_FILES=:/etc/leapp/repos.d/system_upgrade/common/files:/etc/leapp/repos.d/system_upgrade/el7toel8/files', '--setenv=LEAPP_ENABLE_REPOS=rhel-8-for-x86_64-appstream-e4s-rhui-rpms,rhel-8-for-x86_64-baseos-e4s-rhui-rpms,microsoft-azure-rhel8-sap-ha', '--setenv=LEAPP_IPU_IN_PROGRESS=7to8', '--setenv=LEAPP_UNSUPPORTED=0', '--setenv=LEAPP_EXECUTION_ID=ba294cd2-e07d-48cd-898b-19e5d40c5acd', '--setenv=LEAPP_HOSTNAME=rbiba-sap79-2.internal.cloudapp.net', 'dnf', 'install', '-y', '--nogpgcheck', '--setopt=module_platform_id=platform:el8', '--setopt=keepcache=1', '--releasever', u'8.6', '--installroot', '/el8target', '--disablerepo', '*', '--enablerepo', u'rhel-8-for-x86_64-baseos-e4s-rhui-rpms', '--enablerepo', u'microsoft-azure-rhel8-sap-ha', '--enablerepo', u'rhel-8-for-x86_64-appstream-e4s-rhui-rpms', u'rhui-azure-rhel8-sap-ha', 'dnf', 'dnf-command(config-manager)', '--disableplugin', 'subscription-manager'] failed with exit code 1.
    Stderr: Host and machine ids are equal (af1a17ab95da4843b6370fb94f7bbd8c): refusing to link journals
            Failed to synchronize cache for repo 'rhel-8-for-x86_64-baseos-e4s-rhui-rpms', ignoring this repo.
            Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-e4s-rhui-rpms', ignoring this repo.
            Error: Unable to find a match: dnf dnf-command(config-manager)

============================================================
                       END OF ERRORS                        
============================================================
```

With `--target 8.2` and without it, i.e. by default, the system was upgraded to 8.2, and tests are fine. Can it be merged, please?

**Comment by fernflower** [comment]
@alexxa You mean `--product` will allow user to specify which upgrade path to go with, default or sap? 

> With --target 8.2 and without it, i.e. by default, the system was upgraded to 8.2, and tests are fine

Hmm and that is troubling, as default upgrade behaviour without version specified should be upgrade to the latest version.

**Comment by alexxa** [comment]
> @alexxa You mean `--product` will allow user to specify which upgrade path to go with, default or sap?
yes
> > With --target 8.2 and without it, i.e. by default, the system was upgraded to 8.2, and tests are fine
> 
> Hmm and that is troubling, as default upgrade behaviour without version specified should be upgrade to the latest version, which is 8.6. Could you please confirm that you ended up with a rhel 8.2 system when you ran `leapp upgrade` (no target_version passed)?
It's intentional. With SAP it's exceptionally to the earlier releases, not latest. This is written/explained in the PR overview.

**Review by fernflower — APPROVED** [review]
lgtm

**Comment by alexxa** [comment]
@fernflower `--product` was a quick idea, let me think about whether a user case is really legitimate and then we can discuss it elsewhere, ok?

I would still recommend a graceful failure/informative message when `--target` is not available for some reason. Is it possible?

**Comment by fernflower** [comment]
> I would still recommend a graceful failure/informative message when --target is not available for some reason. Is it possible?

Could you please create an issue we could track and discuss? It is out of scope of this patch anyway, but a thing nice to have, would be a shame to forget about it after we merge the patch.

**Comment by pirat89** [comment]
@alexxa  @fernflower  to be honest, not sure whether something like `--product` make sense, as in case that SAP HANA is not installed, no need to tell the product / flavour is sap-hana. But I can imagine e.g. `LEAPP_DEVEL_FLAVOUR`  variable which could define `saphana` for the testing purposes.

@alexxa it's on our board, but regarding it's still possible to get what's wrong from this error, it does not have high prio.

**Pull request merged**
