### PR TITLE
Move "multipathconfread" into common repository

### PR DESCRIPTION
**Pull request by Rezney**
"multipathconfread" actor is compatible with RHEL 8 so let's move
it into common repository. For the moment it will not be of any use but
will help us to fix issue with enabling multipath as we refactored some
parts of related functionality there.

### CODE REVIEW

**Comment by xiachen-rh** [comment]
We were able to upgrade RHEL 8.6 to RHEL 9.0 using this build on the IBM Cloud PowerVS instance.

**Review by pirat89 — APPROVED** [review]

**Pull request merged**
