### PR TITLE
Rename "filename" to "name" in ActiveKernelModule model (closes issue #47)

### PR DESCRIPTION
**Pull request by Seenivasanseeni**
renamed filename to name in ActiveKernelModule implementation and usage of that class

### CODE REVIEW

**Comment by pirat89** [comment]
Additionally, fix commit message: https://chris.beams.io/posts/git-commit/

**Comment by examon** [comment]
@pirat89 Close this one? It looks like it is not moving forward.

**Comment by Seenivasanseeni** [comment]
No no. I will work on this.

**Comment by pirat89** [comment]
@Seenivasanseeni regarding the changes we made in the meantime, rebase the branch against upstream master please. You will have better clue about results of the tests then.

**Comment by bocekm** [comment]
@Seenivasanseeni, do you plan to do the requested changes?

**Comment by Seenivasanseeni** [comment]
Since the branch has moved further, I will start fresh from the new master. I am gonna close this PR.

**Pull request closed without merging**
