### PR TITLE
KDE/GNOME: Use new DESKTOP report tag

### PR DESCRIPTION
**Pull request by bocekm**
Instead of the generic UPGRADE report tag.

Requires: https://github.com/oamg/leapp/pull/612

### CODE REVIEW

**Comment by pirat89** [comment]
leapp-ci test

**Comment by pirat89** [comment]
ah. missing changes in tests.

**Comment by bocekm** [comment]
leapp-ci test

**Comment by bocekm** [comment]
leapp-ci build

**Comment by bocekm** [comment]
The copr build failed already during SRPM building: `KeyError: 'dnf.conf'`. Calling @vojtechsokol and @examon for help.

**Comment by examon** [comment]
leapp-ci build

**Comment by bocekm** [comment]
leapp-ci build

**Comment by pirat89** [comment]
leapp-ci build

**Comment by examon** [comment]
copr build should work now

**Pull request merged**
