### PR TITLE
Bump the upgrade path target to 8.4

### PR DESCRIPTION
**Pull request by Rezney**
With the RHEL 8.4 GA, the expected upgrade patha are going to be:
 - RHEL-ALT 7.6 -> 8.4
 - RHEL 7.9 -> 8.4
 - RHEL for SAP 7.7 -> 8.2

### CODE REVIEW

**Review by pirat89 — APPROVED** [review]

**Review by pirat89 — APPROVED** [review]

**Comment by pirat89** [comment]
leapp-ci build

**Comment by examon** [comment]
leapp-ci build

**Comment by Rezney** [comment]
@pirat89 rebased.

**Comment by pirat89** [comment]
leapp-ci build

**Comment by AloisMahdal** [comment]
Verified with RHEL-7.9 -> RHEL-8.4, RHEL-ALT-7.6 -> RHEL-8.4 using stage CDN:
 * *leapp-repository-0.13.0-0.202104201221Z.20f015e.new_path_to84.PR652.el7_9*

**Review by pirat89 — APPROVED** [review]

**Pull request merged**
