### PR TITLE
Enable "oddjobd" service

### PR DESCRIPTION
**Pull request by Rezney**
Enable "oddjobd" service after authselect convertion, otherwise mkhomedir does not work properly.

### CODE REVIEW

**Comment by AloisMahdal** [comment]
Note that the verification job runs a test that is not 100% done yet and will fail because of a known test issue.  (We're checking for faillock tally migration but turns out that that can't work.)   I'll be keeping an eye on the job and report the correct result here.

**Comment by AloisMahdal** [comment]
I've reviewed the **murphy-ci/ver** result and I can confirm that the oddjobd.service is running and mkhomedir works for all users.

(The failure is as expected due to test limitation which will be resolved before promoting the test.)

**Comment by AloisMahdal** [comment]
So @Rezney  has confirmed the above force-push was just user-facing message text change so the verification applies.

Looks ready to merge..?

**Review by pirat89 — APPROVED** [review]
lgtm.

**Pull request merged**
