### PR TITLE
change the default upgrade path for HANA to 8.6

### PR DESCRIPTION
**Pull request by alexxa**
Since 8.6 has been certified for HANA, and by November time frame all leapp supported CCSPs will have 8.6 image available (Azure and GCP already have it, AWS is in progress), we'd like to change the default upgrade path, which comes without --target option, to 8.6.  With this PR, it's possible to upgrade HANA hosts from 7.9 to 8.6 (default) and from 7.9 to 8.2. The support for 8.2 upgrade path remains till May'2023. 

@mportman12 @berndfinger the corresponding doc change is needed, please.

Thanks!

### CODE REVIEW

**Comment by alexxa** [comment]
@pirat89 review please my first PR to this project =P

**Comment by TomasTomecek** [comment]
(offtopic) The NVRs of builds done by Packit are correct again:

> leapp-upgrade-el8toel9-0.16.0-0.20220809142109523203.pr939.81.g3fa0361.el8.noarch
> leapp-upgrade-el8toel9-deps-0.16.0-0.20220809142109523203.pr939.81.g3fa0361.el8.noarch

@alexxa welcome!

**Review by pirat89 — APPROVED** [review]

**Comment by pirat89** [comment]
@alexxa looks good to me :) can we merge it already? just asking whether this change has been already confirmed or whether we are still waiting for the confirmation. I guess it's already confirmed but double checking before the click on the button :)

**Comment by alexxa** [comment]
@pirat89 yes, our PM gave his bless

**Pull request merged**
