### PR TITLE
Don't skip the test that covers the missing repos issue

### PR DESCRIPTION
**Pull request by fernflower**
If some of the repos that are required for the upgrade are missing upgrade should fail early with an inhibitor.

OAMG-6459

### CODE REVIEW

**Comment by fernflower** [comment]
Okay, maybe having it as a unit test was not such a great idea after all. For rhel7 we are missing dnf module, for rhel8 we are hitting the issue with mocked context.

**Review by pirat89 — APPROVED** [review]
lgtm and seems to be working as expected. I haven't found now any issue

**Pull request merged**
