### PR TITLE
An attempt to support leapp-repository->leapp dependencies

### PR DESCRIPTION
**Pull request by fernflower**
This should teach github action to trigger relevant leapp copr build
if a specific leapp pr number is specified as part of rerun comment.

For example, '/rerun 42' should trigger testing farm service testing for
the leapp-repository version from the pr together with leapp version from
pr 42.

https://issues.redhat.com/browse/OAMG-4988

### CODE REVIEW

**Comment by fernflower** [comment]
@vojtechsokol Please review. The logs of test runs for (/rerun 686) and (/rerun) are in JIRA task and my fork.

**Review by vojtechsokol — COMMENTED** [review]
I think it would be clearer (DRY) to not duplicate `sched_test` and `comment` steps and just modify the already existing steps. E.g. the for the `sched_test` step leave the `request.json` file as it is and add something like
```sh
jq '.environments[0].artifacts += [{"type": "fedora-copr-build", "id": "lepp_copr_id"}]' < request.json
```
and something similar for the `comment` step.

Also `request.json` in `sched_test_leapp` step omits `.environments.variables` list, is this intentional, and if yes, what is the reason behind that?

**Comment by fernflower** [comment]
@vojtechsokol I don't need any environment vars to be passed to the playbook. I wanted to go on and remove environment vars for the request completely, but then it seemed as unrelated change so I went for omitting env vars only in newly written code instead.
Env vars were introduced for the sole purpose of possible embedding the leapp dependencies logic in the playbook, once we have real leapp/leapp-repository deps support we don't need them anymore.

**Comment by fernflower** [comment]
@vojtechsokol Fixed, test run on my fork passed https://github.com/fernflower/leapp-repository/pull/1#issuecomment-916479331

**Comment by vojtechsokol** [comment]
Just a nitpick - the steps that are repeated for leapp and leapp repository (`checkout`\\`checkout_leapp`, `ref_sha`\\`ref_sha_leapp`, `copr_build`\\`copr_build_leapp`, `link_copr`\\`link_copr_leapp`) have the same name, which makes it a bit confusing when looking at the [log](https://github.com/fernflower/leapp-repository/runs/3461823748?check_suite_focus=true). If I wasn't aware of what's going on under the hood, I would be asking why some of the steps are run twice.

Other than that LGTM.

**Review by vojtechsokol — APPROVED** [review]

**Pull request merged**
