### PR TITLE
Removing the checkznet actor - issues fixed by a32d58685

### PR DESCRIPTION
**Pull request by pirat89**
Previously on some machines the networking was broken because of
problems with parsing information about network card from kernel
cmdline.

See the PR #412 for more details:
  https://github.com/oamg/leapp-repository/pull/412

### CODE REVIEW

**Comment by drehak** [comment]
I'm trying to upgrade an s390x machine with this. So far it's been an hour since reboot and I still don't have a functional ssh connection. Sorry, but until I get one, I can't let this pass.
I'll check once more in the morning, perhaps the upgrade just takes time.

**Comment by pirat89** [comment]
leapp-ci build

**Comment by pirat89** [comment]
@drehak Nope, it should be pretty fast. But it is possible that you could hit different issue. Have you checked what's the state of the machine using serial console?

**Comment by drehak** [comment]
@pirat89 From the serial console log, it appears that ultimately, networking broke at some point - from the boot log:

```
[FAILED] Failed to start LSB: Bring up/down networking.
```

dracut seems to be behaving funny:

```
[  492.017513] upgrade[701]:   Running scriptlet: kernel-core-4.18.0-147.0.3.el8_1.s390x           1292/1292
[  492.017542] upgrade[701]: dracut: No '/dev/log' or 'logger' included for syslog logging      
[  492.017578] upgrade[701]: /usr/lib/dracut/modules.d/95qeth_rules/module-setup.sh: line 13: /sys/devices/qeth/*/online: No such file or directory      
[  492.017608] upgrade[701]: /usr/lib/dracut/modules.d/95qeth_rules/module-setup.sh: line 13: /sys/devices/qeth/*/online: No such file or directory      
[  492.017637] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/usr/lib/sysctl.d/10-default-yama-scope.conf': Operation not supported 
[  492.017667] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/hostname': Operation not supported      
[  492.017756] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/machine-id': Operation not supported      
[  492.017848] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/vconsole.conf': Operation not supported      
[  492.017878] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/locale.conf': Operation not supported      
[  492.017915] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/sysctl.conf': Operation not supported      
[  492.017945] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/consolefonts/partialfonts': Operation not supported      
[  492.017975] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/fgGIod': Operation not supported     
[  492.018008] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/qwertz': Operation not supported     
[  492.018038] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/azerty': Operation not supported      
[  492.018081] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/include': Operation not supported    
[  492.018107] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/colemak': Operation not supported    
[  492.018162] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/olpc': Operation not supported      
[  492.018193] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/dvorak': Operation not supported     
[  492.018223] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386/qwerty': Operation not supported     
[  492.018255] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/i386': Operation not supported      
[  492.018294] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/include': Operation not supported      
[  492.018322] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/ppc/include': Operation not supported     
[  492.018353] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/ppc/all': Operation not supported      
[  492.018382] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/sun': Operation not supported      
[  492.018408] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/amiga': Operation not supported      
[  492.018437] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/mac/include': Operation not supported     
[  492.018464] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/mac/all': Operation not supported      
[  492.018492] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/mac': Operation not supported      
[  492.018518] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy/atari': Operation not supported      
[  492.018546] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/legacy': Operation not supported      
[  492.018574] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs//usr/lib/kbd/keymaps/xkb': Operation not supported      
[  492.018600] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/libnl/classid': Operation not supported      
[  492.018626] upgrade[701]: dracut-install: ERROR: installing '/etc/libnl/classid'      
[  492.018662] upgrade[701]: dracut: FAILED: /usr/lib/dracut/dracut-install -D var/tmp/dracut.GktJTG/initramfs /etc/libnl/classid      
[  501.608618] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/modprobe.d/dccp-blacklist.conf': Operation not supported
[  501.608793] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/lvm/lvmlocal.conf': Operation not supported
[  501.608822] upgrade[701]: dracut-install: ERROR: installing '/etc/lvm/lvmlocal.conf'
[  501.608861] upgrade[701]: dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.GktJTG/initramfs -H /etc/lvm/lvmlocal.conf
[  501.608892] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/dasd.conf': Operation not supported
[  501.608923] upgrade[701]: dracut-install: ERROR: installing '/etc/dasd.conf'
[  501.608952] upgrade[701]: dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.GktJTG/initramfs -H /etc/dasd.conf
[  501.608983] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/ld.so.conf': Operation not supported
[  501.609016] upgrade[701]: dracut-install: ERROR: installing '/etc/ld.so.conf'
[  501.609056] upgrade[701]: dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.GktJTG/initramfs /etc/ld.so.conf
[  501.609086] upgrade[701]: cp: setting attributes for '/var/tmp/dracut.GktJTG/initramfs/etc/ld.so.conf.d/kernel-3.10.0-957.el7.s390x.conf': Operation not supported                                                                        
[  501.609113] upgrade[701]: dracut-install: ERROR: installing '/etc/ld.so.conf.d/kernel-3.10.0-957.el7.s390x.conf'
[  501.609140] upgrade[701]: dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.GktJTG/initramfs /etc/ld.so.conf.d/kernel-3.10.0-957.el7.s390x.conf  
```

**Comment by pirat89** [comment]
@drehak  this is expected. The snippet is irrelevant to the issue as during this phase you are not connected. Relevant part of the code to this issue starts after the last reboot (FirstBootPhase e.g.)

**Comment by drehak** [comment]
Tried another s390x upgrade, this time it went fine, networking works, merging.

**Pull request merged**
