### PR TITLE
Update tmt-tests regexes

### PR DESCRIPTION
**Pull request by fernflower**
Morf tests are gone, meet the new max-sst test.

### CODE REVIEW

**Comment by fernflower** [comment]
Proof it works:

/rerun - https://github.com/fernflower/leapp-repository/actions/runs/4014797740

/rerun-sst - https://github.com/fernflower/leapp-repository/actions/runs/4014798264

**Comment by fernflower** [comment]
Rerunning with fernflower/leapp reference

/rerun - https://github.com/fernflower/leapp-repository/actions/runs/4014858408
/rerun-sst - https://github.com/fernflower/leapp-repository/actions/runs/4014859138

**Review by pirat89 — COMMENTED** [review]
waiting for the test results. if tests pass, it can be merged

**Comment by fernflower** [comment]
Nice, max-sst launches just the max-sst tests:
```

+--------------------------------------------------------------------------------+----------+---------+-----------+------------------------------+--------------------------------------+----------+
| SE                                                                             | Stage    | State   | Result    | Environment                  | Guest                                | Runner   |
|--------------------------------------------------------------------------------+----------+---------+-----------+------------------------------+--------------------------------------+----------|
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cockpit                | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | ea80640b-ce15-470f-80ee-d0b4ee135d9b |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cs_apps_0              | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | c940d017-58a2-41c4-8844-7eb5a2c3a57d |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cs_apps_1              | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 0db95df4-267b-44c9-a304-33ffda83d2ed |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cs_infra_services      | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | e8f0754d-26e9-4c5f-a2f4-329f63868e67 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cs_plumbers            | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 35a3883d-4bd9-40a6-88e2-0ddb575f7475 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cs_software_management | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 9cc2c0e1-99a8-4286-a09b-c2fcc622410a |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_cs_system_management   | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 6617fd3c-3e43-4121-801e-bf2340a168e1 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_idm_cs                 | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 716fb1a0-3305-4399-acd2-a5240323977a |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_idm_ds                 | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 625c22df-449e-4d5b-99a7-aa77aaa1e0d6 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_idm_ipa                | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 47bf73b7-856a-44f2-a29d-b977d6ce733e |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_idm_sssd               | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 89d488b7-6ef7-44d8-aa2f-188b7e118e73 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_image_builder          | COMPLETE | OK      | PASSED    | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | f085757c-c226-4204-8cc3-31e9c948632c |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_installer              | RUNNING  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | fc20d88d-857b-4031-9e88-a85786bc7a1c |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_networking             | RUNNING  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 70281a5f-33c4-45c3-8b62-581d22de1c75 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_platform_tools         | RUNNING  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 883ec2cc-921d-4707-b168-aefec8d29e69 |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_rh_samba_storage       | RUNNING  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | bdb2b3bb-95e6-468c-89d8-a2cbff18fb8d |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_security_compliance    | RUNNING  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- | x86_64 RHEL-8.6.0-Nightly S-         | tmt      |
|                                                                                |          |         |           |                              | 78dc13b8-4467-4964-ad73-323817f8d55a |          |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_security_crypto        | CREATED  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- |                                      | tmt      |
| RHEL-8.6.0-Nightly:x86_64:/plans/8to9/tier1/max_sst/sst_security_selinux       | CREATED  | OK      | UNDEFINED | x86_64 RHEL-8.6.0-Nightly S- |                                      | tmt      |
```

@mm0ran Could you please confirm that is the expected test set?

**Comment by mm0ran** [comment]
@fernflower yes, that is the expected list of max_sst tests for the 8to9 upgrade path.

**Comment by fernflower** [comment]
@mm0ran Hmmm but max-sst tests are still being run for /rerun ...

```
| SE                                                                                                                         | Stage              | State   | Result    | Environment                | Guest                                | Runner   |
|----------------------------------------------------------------------------------------------------------------------------+--------------------+---------+-----------+----------------------------+--------------------------------------+----------|
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier0                                                                                  | RUNNING            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 624e2046-8376-4614-9670-bc4fa154cffa |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/grub                                                                             | COMPLETE           | OK      | FAILED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 0bca13e7-71fe-46c7-afda-980eb603434b |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/initram_network                                                                  | COMPLETE           | OK      | FAILED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 491d6534-7b3f-475b-94d5-9d1d0caad921 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cockpit                                                              | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 13a3abec-a4a6-46c8-9fd4-93916bb97592 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cs_apps_0                                                            | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 1ca429ad-a698-4788-8df7-40c58b662777 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cs_apps_1                                                            | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 2a11cfb1-1e7a-4210-b5e8-67ea318c27ca |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cs_infra_services                                                    | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | ae21bf6f-240a-412c-b97c-a2ed1472e978 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cs_plumbers                                                          | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 4131c069-9963-4f89-80b9-9441fc06a9c1 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cs_software_management                                               | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 3339068d-5891-4504-acbf-2749ad4ff148 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_cs_system_management                                                 | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 4980d802-fa5a-4fbd-8ce6-a25bb3431cea |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_idm_cs                                                               | COMPLETE           | ERROR   | UNDEFINED | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | e433fae2-2622-4eae-a095-a40b71c21d30 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_idm_ds                                                               | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 2423c2a3-17c4-47ba-b09a-65539a25b7cb |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_idm_ipa                                                              | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 6749f7b5-fb06-4958-b7fe-0c84a84aa02f |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_idm_sssd                                                             | COMPLETE           | OK      | PASSED    | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | aa6ad096-3bfb-4c26-bb23-c3a271927f92 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_image_builder                                                        | RUNNING            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 2f88152c-744f-4706-acce-aba106c1ab3b |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_installer                                                            | RUNNING            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | 4b039234-60d6-4dd4-beb1-238813fd957f |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_networking                                                           | RUNNING            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- | x86_64 RHEL-7.9-ZStream S-           | tmt      |
|                                                                                                                            |                    |         |           |                            | ab05ee31-547b-41ec-9f7a-2c63490ac471 |          |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_platform_tools                                                       | GUEST_PROVISIONING | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_rh_samba_storage                                                     | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_security_compliance                                                  | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_security_crypto                                                      | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/max_sst/sst_security_selinux                                                     | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/oamg7990_systemd_symlinks                                                        | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/oamg8122_sar_logs                                                                | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/7to8/tier1/upgrade_happy_path                                                               | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/checkanswerfile/integration-checkanswerfile                                     | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/checkfixedmissingnewlineingrubcfg/integration-checkfixedmissingnewlineingrubcfg | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/checkmountoptions/integration-checkmountoptions                                 | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/checkmultiplepackageversion/integration-checkmultiplepackageversion             | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/checknsfd/integration-checknsfd                                                 | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/checkyumpluginsenabled/integration-checkyumpluginsenabled                       | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/postupgrade/e2e/79to84                                                          | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/postupgrade/e2e/79to86                                                          | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/postupgrade/sysctlparsing/sysctl-kernel-param-multiple-equals                   | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/preferredchannel/integration-preferredchannel-invalid-cli-value                 | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/reportbackwardscompatibility/integration-reportbackwardscompatibility           | CREATED            | OK      | UNDEFINED | x86_64 RHEL-7.9-ZStream S- |                                      | tmt      |
| RHEL-7.9-ZStream:x86_64:/plans/integration/targetreleaseversion 
```

Do you have any idea what is wrong with the regex?

**Comment by fernflower** [comment]
Okay, rerunning:

/rerun - https://github.com/fernflower/leapp-repository/actions/runs/4016150760
/rerun-sst - https://github.com/fernflower/leapp-repository/actions/runs/4016152054

**Comment by fernflower** [comment]
Tests run looks good!

**Review by mm0ran — APPROVED** [review]
LGTM!

**Pull request merged**
