### PR TITLE
Move documentation to Read the Docs.

### PR DESCRIPTION
**Pull request by asilveir**
This documentation below is centralized in RTD:

- Best practices
- Dependencies
- Howto Inhibit Upgrade
- Tests

### CODE REVIEW

**Comment by jmikovic** [comment]
I don't think we need 4 files with the same content here... It would be better to have just one file explaining that the docs have been moved and maybe listing what user can find at RtD

**Comment by examon** [comment]
I agree with Jozef. It will be much cleaner with one file. :)

**Comment by jmikovic** [comment]
@asilveir did you forgot to add the new file? :)

**Comment by asilveir** [comment]
> @asilveir did you forget to add the new file? :)

Ops, sorry :(

**Comment by jmikovic** [comment]
I would put it as README there, so it renders in github

**Pull request merged**
