### PR TITLE
Use library function is_inhibitor to check for failures

### PR DESCRIPTION
**Pull request by fernflower**
This patch has to be merged together with leapp's PR677.

OAMG-1429

### CODE REVIEW

**Review by pirat89 — CHANGES_REQUESTED** [review]
Needs the bump of the leapp-framework in the specfile.

**Comment by fernflower** [comment]
Thanks to @MichalHe who helped pinpoint the problem with check_yum_plugins_enabled unit test. Turned out we have a flaw in implementation of create_report_mocked, which caused all BaseListPrimitive fields to be processed incorrectly.
This should be fixing the issue https://github.com/oamg/leapp-repository/pull/905/commits/4064daea230d2b6861654871417fe6d602b46b17

**Review by pirat89 — APPROVED** [review]
tested. the inhibitor works as expected again.

**Pull request merged**
