### PR TITLE
Add mapping based on the installed content

### PR DESCRIPTION
**Pull request by PeterMocary**
Repositories covered by repositories mapping, that are used by installed RPM packages, are used to evaluate expected target repositories on top of evaluating the target repositories from enabled repositories. This covers repositories which might be disabled when upgrading, but should be used to upgrade installed packages during the upgrade.

Jira ref.: OAMG-7304

### CODE REVIEW

**Comment by fernflower** [comment]
@PeterMocary I have added a unit test, hope you don't mind :) 
@pirat89 Sorry to bother you, but since I am a co-author now it's not ok for me to self-merge this patch. Would you mind to take a look? LGTM

**Comment by pirat89** [comment]
Works as expected:
```
Type: TargetRepositories
Message_data:
{
    "custom_repos": [],
    "rhel_repos": [
        {
            "repoid": "rhel-9-for-x86_64-appstream-rpms"
        },
        {
            "repoid": "rhel-9-for-x86_64-baseos-rpms"
        },
        {
            "repoid": "rhel-9-for-x86_64-rt-rpms"
        }
    ]
}

```
the original RT repository has been disabled

**Review by pirat89 — APPROVED** [review]
lgtm and seems to be working as expected.

**Pull request merged**
