### PR TITLE
Remove test leapp repository

### PR DESCRIPTION
**Pull request by bocekm**
- and remove test actor/model/topic in common leapp repo
- the test model was causing [a traceback](http://pastebin.test.redhat.com/693953) which could be fixed but there's no need for a test repo anymore

### CODE REVIEW

**Comment by bocekm** [comment]
I work from another computer and now I've realized I hadn't submitted the patch from my fork. If needed, I'll redo that in my fork and create a new PR.

**Comment by radomil** [comment]
LGTM

**Comment by vinzenz** [comment]
@examon Is it still used?

**Comment by Rezney** [comment]
@bocekm there is no "required" in repos/common/models/test.py you are removing

**Pull request merged**
