### PR TITLE
cli: Move leapp cli commands from leapp to leapp-repository

### PR DESCRIPTION
**Pull request by vinzenz**
This patch introduces the `leapp` top-level commands moved over
from the leapp framework git repository. The upgrade package has
been split in order to facilitate the new approach of having one
command per package.

Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Comment by pirat89** [comment]
@vinzenz here is solution for the packaging: https://github.com/vinzenz/leapp-repository/pull/5

**Comment by pirat89** [comment]
@vinzenz  btw, do not forget on `framework-version`  :)

**Comment by pirat89** [comment]
testing in progress btw

**Comment by vinzenz** [comment]
> @vinzenz here is solution for the packaging: [vinzenz#5](https://github.com/vinzenz/leapp-repository/pull/5) (tested with leapp build for pr 700)

Merged

**Comment by vinzenz** [comment]
> @vinzenz btw, do not forget on `framework-version` :)

Done

**Review by pirat89 — APPROVED** [review]
lgtm. going to run the regression tests. manually tested, everything seems ok so far

**Comment by pirat89** [comment]
* integration tests are broken - ignoring
* e2e tests have problems to install specific combination of leapp and leapp-repository. We are going to work on that little bit yet.
* all other tests passed

It's possibly I will do a rebase with changed commit msgs to try another one thing. But so far I am ok with merging today if we do not resolve the problems of broken tests..

**Review by pirat89 — DISMISSED** [review]

**Review by pirat89 — APPROVED** [review]
Just squashed commits and updated the commit msg.

**Pull request merged**
