### PR TITLE
actor: firewalld: support 0.8.z

### PR DESCRIPTION
**Pull request by erig0**
Prior to this change the actor only supported firewalld-0.9.z and later.

Relevant differences between 0.9.z and 0.8.z:

- Policies don't exist (new in 0.9.0)
- Zones use a tuple based API

Fixes: rhbz2101909

### CODE REVIEW

**Comment by erig0** [comment]
review please

**Comment by erig0** [comment]
> review please

bump

**Comment by pirat89** [comment]
@erig0  Hi Eric. It seems good to me. As there is BZ connected to this PR, can you find someone (QE from your team) who will cover the testing and set the person in the BZ? Unless you plan to close the BZ as upstream, then we are ok with anyone who test it before the merge.

**Comment by erig0** [comment]
> @erig0 Hi Eric. It seems good to me. As there is BZ connected to this PR, can you find someone (QE from your team) who will cover the testing and set the person in the BZ?

Done.

**Comment by erig0** [comment]
@pirat89 , can this be merged now? Or do you need QA done before merge?

**Comment by pirat89** [comment]
@erig0 thanks. no need unless QE wants to test it before the merge. running sanity tests

**Comment by holser** [comment]
@pirat89 @erig0 I have manually tested the patch in my system. leapp didn't throw python exception on RHEL 8.4. It upgraded the system so my big +1 for patch.

LGTM, tested, approved.

**Review by holser — APPROVED** [review]
It looks good to me. Tested on 8.4. It passed preupgrade/upgrade and phase 2.

**Review by pirat89 — APPROVED** [review]
Sanity tests passed too. merging

**Pull request merged**
