### PR TITLE
SKIP RHSM (devel)

### PR DESCRIPTION
**Pull request by pirat89**
For the testing purposes we need to skip use of subscription-manager
and go on just with custom repositories. This is now possible with
the patch when proper custom repositories are set. The solution will
be reworked in future.

To skip the subscription-manager, set
```
LEAPP_DEVEL_SKIP_RHSM=1
```

Keep in mind that when the option is used, user (devel/tester) is reponsible that proper repositories are delivered. There are skipped several checks regarding the installation repositories (see `CustomTargetRepository` model; the repo file has to exist already on the system)

### CODE REVIEW

**Comment by jmikovic** [comment]
I'm missing some documentation explaining how to make use of the skip, how to setup custom repos for upgrade.

**Comment by jmikovic** [comment]
please rebase so I can test (ATM leapp is being removed during upgrade)

**Comment by pirat89** [comment]
> I'm missing some documentation explaining how to make use of the skip, how to setup custom repos for upgrade.

Commit message :) I will update description of PR

**Comment by pirat89** [comment]
rebased

**Pull request merged**
