### PR TITLE
Add CentOS signed packages support

### PR DESCRIPTION
**Pull request by andrewlukoshko**
This PR adds CentOS 7 and 8 keys as valid

### CODE REVIEW

**Comment by evgeni** [comment]
I was pondering about LEAPP and CentOS a bit, and after thinking about this issue a bit, came up with the following alternative:
https://github.com/oamg/leapp-repository/pull/876

What do you think?

**Comment by fernflower** [comment]
Do we still need this PR?

**Comment by pirat89** [comment]
I think we could close it as it will be covered by https://github.com/oamg/leapp-repository/pull/876. @andrewlukoshko  wdyt?

**Comment by andrewlukoshko** [comment]
Sure. https://github.com/oamg/leapp-repository/pull/876 is a better way to do this.

**Comment by fernflower** [comment]
Thanks! So closing.

**Pull request closed without merging**
