### PR TITLE
Do not remove java from the transaction

### PR DESCRIPTION
**Pull request by Rezney**
The issue described in the BZ (mentioned in the code) has been
resolved.

### CODE REVIEW

**Comment by bocekm** [comment]
A new BZ to introduce the fix in the 8.2 z-stream: https://bugzilla.redhat.com/show_bug.cgi?id=1871709.

**Comment by bocekm** [comment]
Included in the RHBA-2020:58734-02 for RHEL-8.2.0.Z. @AloisMahdal, before I merge this, can you please test the upgrade with the `java-11-openjdk-11.0.8.10-1.el8_2` attached to the Erratum?

**Comment by AloisMahdal** [comment]
leapp-ci build

**Comment by AloisMahdal** [comment]
Old build is gone and new one fails.  I presume rebase will be needed as well (and could be cause of failure.)

**Comment by bocekm** [comment]
Rebased.

**Comment by bocekm** [comment]
leapp-ci build

**Comment by vojtechsokol** [comment]
leapp-ci build

**Comment by AloisMahdal** [comment]
Verified with *leapp-repository-0.11.0-0.202009041445Z.201751b.stop_removing_java.PR516.el7_6* and latest internal PES data snapshot(s).

**Review by pirat89 — APPROVED** [review]

**Pull request merged**
