### PR TITLE
Fix cephvolume actor

### PR DESCRIPTION
**Pull request by holser**
Change cephvolume behavior to return None when ceph-osd container is not found.

Fixes: rhbz#2141393

### CODE REVIEW

**Comment by holser** [comment]
review please

**Review by jbadiapa — CHANGES_REQUESTED** [review]
I will remove line 15 [1] as the initialization of the var is not needed.

[1] https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/common/actors/cephvolumescan/libraries/cephvolumescan.py#L15

**Comment by asm0deuz** [comment]
@holser Hi! I am thinking about another solution which would require less changes. I will test it and open another PR if it works.

**Review by guits — DISMISSED** [review]

**Comment by asm0deuz** [comment]
@holser Your solution is the correct one. I have the same comment as @jbadiapa .

**Comment by holser** [comment]
> I will remove line 15 [1] as the initialization of the var is not needed.
> 
> [1] https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/common/actors/cephvolumescan/libraries/cephvolumescan.py#L15

Thanks. I have updated PR with proposed change

**Comment by holser** [comment]
> @holser Your solution is the correct one. I have the same comment as @jbadiapa .

Thanks a lot for comments. I have updated PR with proposed change.

**Comment by jbadiapa** [comment]
lgtm
thanks,

**Comment by holser** [comment]
@asm0deuz @guits @pirat89 Please review when you have time

**Review by pirat89 — APPROVED** [review]
lgtm. waiting for qe ack in the BZ + confirmation from qe it works before the merge.

**Comment by pirat89** [comment]
we hav ethe confirmation from the QE, so merging.

**Pull request merged**
