### PR TITLE
Run 8to9 regression tests on /rerun

### PR DESCRIPTION
**Pull request by fernflower**
With the need to add 8to9 regression tests along with 7to8 refactor of tmt-tests workflow needs to be done.

### CODE REVIEW

**Comment by fernflower** [comment]
leapp-ci build

**Comment by fernflower** [comment]
@examon Running /rerun here won't be relevant as it runs old version of github action https://github.com/oamg/leapp-repository/actions/runs/1649288930/workflow

**Comment by Rezney** [comment]
@fernflower Maybe a stupid question but what is substituting the `Generate a tmt test request` "task" ?

**Comment by fernflower** [comment]
@Rezney A totally valid question - I moved out tft run scheduling into a composite action that could be reused https://github.com/fernflower/testing-farm-service-action/blob/main/action.yml#L64

**Comment by fernflower** [comment]
@Rezney @pirat89 Transferred ownership of composite action to oamg, updated repository name.
Successful run on my fork - https://github.com/fernflower/leapp-repository/actions/runs/1649999056 
(Here https://github.com/fernflower/leapp-repository/actions/runs/1649999056/workflow you can check what version of github action was actually run, note the oamg/tetsing-farm-service-action there)

**Review by Rezney — APPROVED** [review]
Looks good to me...

**Pull request merged**
