### PR TITLE
grubdevname: Python3 compatibility fix

### PR DESCRIPTION
**Pull request by vinzenz**
Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Review by pirat89 — COMMENTED** [review]
we should cover this change by unit-test

**Comment by vinzenz** [comment]
it is, already covered that's how I figured out that i broke python2 with
the initial implementation

**Comment by pirat89** [comment]
aaah, great!

**Review by Rezney — APPROVED** [review]
The tests and the upgrade itself passed locally.

**Comment by pirat89** [comment]
ahh..how we just simply overlooked the failed tests? @vinzenz  @Rezney 

btw, I am almost sure I've seen passed tests before. so I am really confused I see the fail right now. Am I the only one who remember the very same thing or you realized the green test results too? O_o

**Pull request merged**
