### PR TITLE
required changes for an in-place upgrade of a SAP HANA system...

### PR DESCRIPTION
**Pull request by berndfinger**
...from RHEL 7.9 to RHEL 8.4

### CODE REVIEW

**Review by vinzenz — APPROVED** [review]

**Comment by vinzenz** [comment]
LGTM - Thanks!

**Comment by Rezney** [comment]
Guys, I am wondering, don't we want to change also:

repos/system_upgrade/common/libraries/config/version.py

```python
_SUPPORTED_VERSIONS = {
    # Note: 'rhel-alt' is detected when on 'rhel' with kernel 4.x
    '7': {'rhel': ['7.9'], 'rhel-alt': ['7.6'], 'rhel-saphana': ['7.7']},
    '8': {'rhel': ['8.5', '8.6']},
}
```

As the upgrade from 7.9 will get otherwise inhibited.

**Comment by pirat89** [comment]
@Rezney I would expect you are right but I expect this has been tested...

**Comment by vinzenz** [comment]
Well shame on me, I didn't test this - @Rezney good catch btw

@berndfinger  To prevent the inhibitor, you'd have to update `repos/system_upgrade/common/libraries/config/version.py`
```python
_SUPPORTED_VERSIONS = {
    # Note: 'rhel-alt' is detected when on 'rhel' with kernel 4.x
    '7': {'rhel': ['7.9'], 'rhel-alt': ['7.6'], 'rhel-saphana': ['7.7']},
    '8': {'rhel': ['8.5', '8.6']},
}
```
Needs to be changed to 
```python
_SUPPORTED_VERSIONS = {
    # Note: 'rhel-alt' is detected when on 'rhel' with kernel 4.x
    '7': {'rhel': ['7.9'], 'rhel-alt': ['7.6'], 'rhel-saphana': ['7.9']},
    '8': {'rhel': ['8.5', '8.6']},
}
```

**Pull request merged**
