### PR TITLE
[WIP] Handle modules in PES event scanner

### PR DESCRIPTION
**Pull request by drehak**
Now that modular packages are represented in PES data, we need to integrate that data into our PES event scanner actor.
Larger refactors are necessary because a dict in the format `{'name': 'repository'}` is not enough to handle packagesets with modular packages.

Work in progress, please do not review.

### CODE REVIEW

**Comment by examon** [comment]
leapp-ci build

**Comment by examon** [comment]
leapp-ci build

**Comment by drehak** [comment]
Back at work here. Just rebased on current master, going to briefly document the changes on our board and fix the failing tests.

**Comment by drehak** [comment]
Existing units tests finally pass, next up is writing some unit tests for working with modular packages and applying feedback on the `modularity.py` library.

**Comment by drehak** [comment]
Closing the PR because it's too large and smaller PRs like #667 will be merged instead.
My latest commits will still be pushed to this branch for a while.

**Pull request closed without merging**
