### PR TITLE
Enable/Fix s390x

### PR DESCRIPTION
**Pull request by pirat89**
Enable upgrade on s390x machines + skip scanning of GRUB2 config on the s390x arch (there is not GRUB2, but ZIPL).

@vinzenz: Currently we do not handle ZIPL, so I am ok to remove the commit modifyinf `ARCH_SUPPORTED` tuple in `architecture`. More important is here the skip of GRUB scanner.

### CODE REVIEW

**Comment by pirat89** [comment]
leapp-ci build

**Comment by pirat89** [comment]
leapp-ci build

**Comment by pirat89** [comment]
@asilveir  This should affect only s390x arch.

**Comment by vinzenz** [comment]
Tested as base of my commits and works as expected.

**Pull request merged**
