### PR TITLE
Refactor handling of GPG keys into separate library and verify no unexpected keys are installed in ApplicationsPhase

### PR DESCRIPTION
**Pull request by Jakuje**
This adds the requested check into the application phase after first boot. It might make sense to move it even earlier to `FirstBootPhase` as suggested by @pirat89 previously.
We would also like to implement similar check that could be executed on each and every stage of the container installation given a overlay context, but I did not get that deep yet so consider this for now as WIP/Draft.

### CODE REVIEW

**Comment by fernflower** [comment]
Hmm I see leapp-upgrade package installation failure for 7->8 tests
```
---> Package libreport-filesystem.x86_64 0:2.1.11-53.el7 will be installed
---> Package librhsm.x86_64 0:0.0.3-3.el7_9 will be installed
---> Package libsolv.x86_64 0:0.6.34-4.el7 will be installed
---> Package python2-leapp.noarch 0:0.15.1-1.el7_9 will be installed
--> Processing Dependency: leapp-framework < 4 for package: leapp-upgrade-el7toel8-0.18.0-0.202307251057Z.9da15b0.HEAD.PR1101.el7.noarch
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

---^---^---^---^---^---

Stderr:
---v---v---v---v---v---
Warning: Permanently added '10.31.42.140' (ECDSA) to the list of known hosts.

Error: Package: leapp-upgrade-el7toel8-0.18.0-0.202307251057Z.9da15b0.HEAD.PR1101.el7.noarch (/leapp-upgrade-el7toel8-0.18.0-0.202307251057Z.9da15b0.HEAD.PR1101.el7.noarch)
           Requires: leapp-framework < 4
           Available: python2-leapp-0.15.1-0.202307171723Z.154e1c5.HEAD.el7.noarch (copr:copr.fedorainfracloud.org:group_oamg:leapp)
               leapp-framework = 4.0
           Available: python2-leapp-0.15.1-0.20230711084102271604.pr818.11.g0d530a3.el7.noarch (copr:copr.fedorainfracloud.org:group_oamg:leapp)
               leapp-framework = 4.0
           Available: python2-leapp-0.15.1-0.20230717153001019925.pr836.18.gfc84b43.el7.noarch (copr:copr.fedorainfracloud.org:group_oamg:leapp)
               leapp-framework = 3.1
           Available: python2-leapp-0.15.1-1.el7_9.noarch (rhel-extras)
               leapp-framework = 3.1
           Installing: python2-leapp-0.15.1-100.20230717172642338352.master.18.g154e1c5.el7.noarch (copr:copr.fedorainfracloud.org:group_oamg:leapp)
               leapp-framework = 4.0

---^---^---^---^---^---
```

**Comment by fernflower** [comment]
From the nature of tests failure the patch needs a rebase.

**Comment by Jakuje** [comment]
rebased on current master.

**Comment by pirat89** [comment]
@Jakuje  rebase please

**Comment by Jakuje** [comment]
> @Jakuje rebase please

Done

**Review by pirat89 — APPROVED** [review]
waiting for tests and doing also some manual testing yet. but lgtm otherwise.

**Comment by pirat89** [comment]
fixed some crashes and updated tests to improve the test coverage. waiting for results of integration tests

**Comment by pirat89** [comment]
...making  py2 pylint on rhel7 happy :sob:

**Comment by pirat89** [comment]
The failed AWS test `testing-farm:RHEL-7.9-rhui-x86_64:sanity-7to8-aws-e2e` is caused by infra issue. Ignorring.

**Comment by pirat89** [comment]
manual testing passed \o/ waiting for upstream tests.

**Comment by pirat89** [comment]
upstream tests passed. merging!! @Jakuje  thanks! for the contribution!

**Review by pirat89 — APPROVED** [review]
everything seems to be working correctly.

**Pull request merged**
