### PR TITLE
WIP: Add basic unit test for SCTP

### PR DESCRIPTION
**Pull request by adka1408**
I wrote first little test, I'm not sure if it's ok, it needs to be checked.

### CODE REVIEW

**Comment by pirat89** [comment]
As you can see, you need to fix it so tests will pass (at least in travis, leapp-ci is broken now). Additionally, you have there test that should prove just one functionality.  I expect minimally two tests there.

**Comment by jmikovic** [comment]
please rebase

**Comment by vojtechsokol** [comment]
leapp-ci build

**Comment by asilveir** [comment]
closing in favor of #355

**Pull request closed without merging**
