### PR TITLE
.packit.yaml: adjust `post_install_script` for RHEL 7.9

### PR DESCRIPTION
**Pull request by mkluson**
Remove enabling repos step from .packit.yaml, it was moved to TF, where it logically belongs to.

### CODE REVIEW

**Comment by mkluson** [comment]
Fails on RHEL-7.9-rhui is expected. Changes in TF have to be deployed yet.

**Comment by pirat89** [comment]
@mkluson converting it to draft until the changes in TF are delivered. switch it back to ready for review once everything is set. thanks

**Comment by mm0ran** [comment]
Closing this, as it has been implemented in https://github.com/oamg/leapp-repository/pull/1252

**Pull request closed without merging**
