### PR TITLE
Fix "wrong-import-order" pylint errors

### PR DESCRIPTION
**Pull request by Rezney**

### CODE REVIEW

**Comment by vojtechsokol** [comment]
Are you sure this is correct? PEP8 says this about import grouping:

> Imports should be grouped in the following order:
> 1. Standard library imports.
> 1. Related third party imports.
> 1. Local application/library specific imports.
> 
> You should put a blank line between each group of imports.

So `selinux` and `pydev` being third party imports should be separated from `re` (stdlib) and `leapp.*` imports.

**Comment by pirat89** [comment]
Agree with @vojtechsokol - this should be even in the guidelines already.

**Comment by fernflower** [comment]
@Rezney did pylint complain about the import order before your patch? I could not trigger this violation manually.

**Comment by jmikovic** [comment]
@fernflower @pirat89 @vojtechsokol it occured in PR#53
here is link to failing travis https://travis-ci.org/oamg/leapp-repository/builds/543728585
I can reproduce it every time running make lint

**Comment by fernflower** [comment]
https://github.com/oamg/leapp-repository/pull/244 - this should fix the issue

**Pull request closed without merging**
