### PR TITLE
Add leapp pkgs rpm verification into the breadcrumbs

### PR DESCRIPTION
**Pull request by Rezney**
Add leapp pkgs rpm verification into the breadcrumbs.

### CODE REVIEW

**Comment by fernflower** [comment]
@Rezney Is this still needed or can we close this?

**Comment by pirat89** [comment]
yes, we should put these as part of breadcrumbs.

**Comment by Rezney** [comment]
Result:
```
      "leapp_file_changes": [
        {
          "file_name": "   /usr/share/leapp-repository/repositories/system_upgrade/el8toel9/actors/sssdfacts/__pycache__/actor.cpython-36.pyc",
          "result": "S.5....T."
        },
        {
          "file_name": "   /usr/share/leapp-repository/repositories/system_upgrade/el8toel9/actors/sssdfacts/actor.py",
          "result": "S.5....T."
        }
      ],
```

**Comment by Rezney** [comment]
@fernflower @pirat89 This should be ready.

**Review by pirat89 — APPROVED** [review]

**Comment by pirat89** [comment]
waiting for the test results. can be merged after sanity testing pass

**Comment by pirat89** [comment]
@Rezney  I knew I forgot something. nevermind. it's going to the next release instead.

**Pull request merged**
