### PR TITLE
Rework the NetworkManagerUpdateClientId actor (v2)

### PR DESCRIPTION
**Pull request by bengal**
Move the external tool code into a library and convert it to use nmcli instead of the GObject introspection library.

See also #69

### CODE REVIEW

**Comment by bengal** [comment]
Sorry, I couldn't test the PR because upgrade using the vagrant box fails (even without my PR):

https://gist.github.com/bengal/6df10c10b4d9ae292cc0b4f944a6062d

**Comment by jmikovic** [comment]
@bengal please update the vagrant box, we just merged a fix for this error

**Comment by bengal** [comment]
> @bengal please update the vagrant box, we just merged a fix for this error

It works now, thanks!

**Comment by examon** [comment]
leapp-ci build

**Pull request merged**
