### PR TITLE
report which OS release was detected as unsupported

### PR DESCRIPTION
**Pull request by evgeni**
includes #1234 to prevent merge conflicts

### CODE REVIEW

**Comment by pirat89** [comment]
@evgeni lgtm. I like it. But thinking about that, when you already started these changes, that we could add also remediation instructions, somthing like:
```python
pkg_manager = 'yum' if version.get_source_major_version == '7' else 'dnf
reporting.Remediation(hint=(
    'Update your system using {pkg_manager} to the version of the system supported for the in-place upgrade.'
    .format(pkg_manager=pkg_manager)
))
```

**Comment by evgeni** [comment]
Personally, I wouldn't do that.
The unsupported systems will be Alma, Rocky etc, and they *can't* be upgraded using `dnf`, so posting that remediation would be wrong

**Comment by pirat89** [comment]
Interesting. Oki, let's skip it for now.

**Review by pirat89 — APPROVED** [review]

**Comment by pirat89** [comment]
well, when we add check for the `rhel` system, then we can clearly skip this whole report from my pov. e.g. for centos stream this report does not provide any value at all. and I have no idea about requirements from almalinux/rocky at all. so from my pov, it's matter of time we update this particular actor. but it's for me interesting that almalinux could not use yum/dnf for the update of the system. that's for me hoenstly little bit weird. so I guess I am missing here something.

**Comment by evgeni** [comment]
Well, can you use yum/dnf to upgrade RHEL from 8 to 9? Alma/Rocky/Oracle has the same issue. You gotta Leapp major versions.

**Comment by pirat89** [comment]
no, but you can use DNF do update to newer minor version. This is about trying to upgrade FROM unsupported version of the system.

**Comment by evgeni** [comment]
Ooooh. Now I get what you wanted to do!
```
if (on 8.9) {
    tell user to update to 8.10 first using dnf
}

**Pull request merged**
