### PR TITLE
Move CIFS check actor to common

### PR DESCRIPTION
**Pull request by fernflower**
The check should be the safe for 7to8 and 8to9 upgrade. Also add logic to skip the check in case
LEAPP_DEVEL_INITRAM_NETWORK env var is set.

OAMG-8490

### CODE REVIEW

**Review by matejmatuska — APPROVED** [review]
Tested on both 7->8 and 8->9 with `cifs` entry in `/etc/fstab` and the upgrade was properly inhibited with message:
```
Upgrade has been inhibited due to the following problems:
    1. Inhibitor: Use of CIFS detected. Upgrade can't proceed
```
With `LEAPP_DEVEL_INITRAM_NETWORK` set, the upgrade was not inhibited, as expected.

LGTM

**Review by MichalHe — APPROVED** [review]
LGTM

**Comment by MichalHe** [comment]
The only integration tests that are failing are those testing for supplying invalid `pes-events.json` file and expecting leapp to crash due to unhandled exception. However, leapp not gracefully handling an invalid file is a bug that has been fixed with [PR1026](https://github.com/oamg/leapp-repository/pull/1026). There is already a patch correcting the integration tests. #

**Pull request merged**
