### PR TITLE
Add snactor workflow sanity-check

### PR DESCRIPTION
**Pull request by Rezney**

### CODE REVIEW

**Comment by Rezney** [comment]
leapp-ci build

**Comment by examon** [comment]
leapp-ci build

**Comment by pirat89** [comment]
leapp-ci build

**Comment by pirat89** [comment]
@Rezney rebase pls :)

**Comment by Rezney** [comment]
@pirat89 aah, yep makes sense.

**Comment by Rezney** [comment]
@pirat89 rebased

**Comment by bocekm** [comment]
We have a new error thanks to this sanity check, related to @pirat89's https://github.com/oamg/leapp-repository/pull/363:
`FAIL: The following messages are attempted to be consumed before they are produced: TargetRHSMInfo`

**Comment by bocekm** [comment]
leapp-ci build

**Comment by bocekm** [comment]
@Rezney, please rebase, the https://github.com/oamg/leapp-repository/pull/369 fixed the above-mentioned test failure.

**Pull request merged**
